version: '3.8'

services:
  vps-dashboard:
    build: .
    container_name: vps-dashboard
    restart: always
    ports:
      - "80:3000"
    volumes:
      # Conecta ao socket do Docker da máquina hospedeira para monitorar containers
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jacare-network
    environment:
      - PORT=3000
      - DASHBOARD_USER=bsbvinidesousa@gmail.com
      - DASHBOARD_PASS=Cap@2026

networks:
  jacare-network:
    name: jacare-network
    external: true

